# Generated by Django 6.0.4 on 2026-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imge', models.FileField(upload_to='tourist/')),
                ('name_place', models.CharField(max_length=100)),
                ('expresion', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
