# Generated by Django 6.0.4 on 2026-06-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_users_number_sms_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='commnts_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.users')),
            ],
        ),
    ]
