# Generated by Django 6.0.4 on 2026-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0003_remove_upload_tourist_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_tourist',
            name='image',
            field=models.FileField(default='rtrt', upload_to='tourist/'),
            preserve_default=False,
        ),
    ]
