# Generated by Django 6.0.4 on 2026-06-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0004_upload_tourist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_tourist',
            name='image',
        ),
    ]
