# Generated by Django 6.0.4 on 2026-06-19 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0005_remove_upload_tourist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='tourist/')),
                ('witch_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manag.upload_tourist')),
            ],
        ),
    ]
