# Generated by Django 6.0.4 on 2026-06-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0006_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_tourist_dongi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_place', models.CharField(max_length=100)),
                ('expresion', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='upload_image',
            name='witch_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manag.upload_tourist_dongi'),
        ),
    ]
