# Generated by Django 6.0.4 on 2026-06-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0007_upload_tourist_dongi_alter_upload_image_witch_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='witch_tour_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manag.upload_tourist_dongi'),
        ),
        migrations.AlterField(
            model_name='upload_image',
            name='witch_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manag.upload_tourist'),
        ),
    ]
