# Generated by Django 6.0.4 on 2026-06-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manag', '0008_upload_image_witch_tour_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_image',
            name='witch_tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manag.upload_tourist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload_image',
            name='witch_tour_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manag.upload_tourist_dongi'),
            preserve_default=False,
        ),
    ]
