# Generated by Django 6.0.4 on 2026-06-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_commnts_user'),
        ('manag', '0010_alter_upload_image_witch_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_image',
            name='which_user_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.commnts_user'),
        ),
    ]
